#!/usr/bin/env bash
# Build libtalloc.so, the hierarchical memory pool allocator PRoot depends on.
#
# talloc is compiled straight from talloc.c against a small bionic portability
# header (bionic-replace.h) rather than through Samba's waf. See the long comment
# at the top of that header for why; the short version is that cross-compiling
# waf requires a hand-maintained "cross answers" file whose wrong answers fail
# silently, and talloc.c's real portability surface is small enough to state.
. "$(dirname "$0")/../lib/common.sh"

setup_toolchain
fetch_tarball "$TALLOC_URL" "$TALLOC_SHA256" "talloc-$TALLOC_VERSION.tar.gz"

SRC="$BUILD_ROOT/src/talloc-$TALLOC_VERSION"
BUILD="$BUILD_ROOT/build/talloc"
rm -rf "$SRC" "$BUILD"
mkdir -p "$SRC" "$BUILD" "$BUILD_ROOT/src"
tar -xzf "$DL_DIR/talloc-$TALLOC_VERSION.tar.gz" -C "$BUILD_ROOT/src"
[ -f "$SRC/talloc.c" ] || die "talloc.c not found under $SRC"

# waf normally derives these from the version and bakes them into config.h.
# talloc.c #errors out if they disagree with talloc.h, so a wrong split here is
# caught at compile time rather than becoming a runtime magic-value mismatch.
IFS='.' read -r TV_MAJOR TV_MINOR TV_RELEASE <<< "$TALLOC_VERSION"
note "version  $TALLOC_VERSION -> MAJOR=$TV_MAJOR MINOR=$TV_MINOR RELEASE=$TV_RELEASE"

# talloc.c does `#include "replace.h"` unconditionally. The real file is named
# bionic-replace.h in this repository so it is never mistaken for Samba's own
# replace.h; this generated one-liner is the bridge, and it lives in the build
# directory rather than the source tree so the naming stays unambiguous.
cat > "$BUILD/replace.h" <<'EOF'
/* Generated by prebuilts/talloc/build.sh. Do not edit. */
#include "bionic-replace.h"
EOF

note "compiling talloc.c"
"$CC" \
    -shared -fPIC -O2 \
    -std=gnu11 \
    -Wall \
    $REPRO_CFLAGS \
    -DTALLOC_BUILD_VERSION_MAJOR="$TV_MAJOR" \
    -DTALLOC_BUILD_VERSION_MINOR="$TV_MINOR" \
    -DTALLOC_BUILD_VERSION_RELEASE="$TV_RELEASE" \
    -I"$BUILD" -I"$PREBUILTS_DIR/talloc" \
    -I"$SRC" \
    -o "$BUILD/libtalloc.so" \
    "$SRC/talloc.c" \
    -Wl,-soname,libtalloc.so.2 \
    -Wl,-z,max-page-size=16384 \
    -Wl,--build-id=none

assert_arm64 "$BUILD/libtalloc.so"

# PRoot links against -ltalloc and resolves these at runtime. If the constructor
# is missing, talloc silently falls back to a fixed magic value, the exact
# hardening regression bionic-replace.h exists to prevent, so check for it.
note "sanity checks"
syms=$("$TOOLCHAIN/bin/llvm-nm" -D --defined-only "$BUILD/libtalloc.so")
for want in talloc_named_const _talloc_free talloc_strdup _talloc_realloc; do
    contains "$syms" " $want" || die "libtalloc.so does not export $want"
done
printf '    %s exported symbols\n' "$(printf '%s\n' "$syms" | wc -l)"

dyn=$("$READELF" --dynamic "$BUILD/libtalloc.so")
contains "$dyn" "libtalloc.so.2" || die "SONAME is not libtalloc.so.2; PRoot will not find it"
printf '    SONAME libtalloc.so.2\n'

# The randomised-magic constructor. Its absence means HAVE_CONSTRUCTOR_ATTRIBUTE
# did not take effect and talloc's anti-corruption hardening is off.
contains "$dyn" "INIT_ARRAY" \
    || warn "no INIT_ARRAY: talloc's randomised magic constructor did not link in"

install_artifact "$BUILD/libtalloc.so" libtalloc.so
